const KEY='evo.seal.v0.registry';const $=id=>document.getElementById(id);const enc=new TextEncoder();
const token='0x622b09038bc1ae90ee13a35ba5756b931d9dcc9f';
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function hex(buf){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function shaBytes(bytes){if(!crypto?.subtle)throw new Error('Web Crypto no disponible');return hex(await crypto.subtle.digest('SHA-256',bytes))}
const shaText=t=>shaBytes(enc.encode(t));async function shaFile(f){return shaBytes(new Uint8Array(await f.arrayBuffer()))}
function canonical(o){return JSON.stringify(Object.keys(o).sort().reduce((a,k)=>(a[k]=typeof o[k]==='string'?o[k].trim():o[k],a),{}))}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return []}}function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function rand(){const b=new Uint8Array(16);crypto.getRandomValues(b);return hex(b)}
function renderList(){const r=load().slice().reverse(),root=$('sealList');root.innerHTML=r.length?r.slice(0,8).map(s=>`<button class="btn item" data-id="${s.sealId}"><b>${esc(s.title)}</b><br><span class="mono">${s.sealId}</span></button>`).join(''):'<div class="empty">Sin sellos locales todavía.</div>';root.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{$('verifyId').value=b.dataset.id;location.hash='#verify';verify()})}
function rows(s,extra=''){return `<span class="status ok">✓ REGISTERED</span>${extra}<div class="kv"><span>Seal ID</span><b class="mono">${s.sealId}</b></div><div class="kv"><span>Nombre</span><b>${esc(s.title)}</b></div><div class="kv"><span>Emisor</span><span>${esc(s.issuer)}</span></div><div class="kv"><span>Fecha</span><span>${s.createdAt}</span></div><div class="kv"><span>Asset hash</span><span class="mono">${s.assetHash||'N/A'}</span></div><div class="kv"><span>Estado</span><span class="status warn">LOCAL V0 · 0 EVO</span></div>`}
$('sealForm').onsubmit=async e=>{e.preventDefault();try{const file=$('file').files[0],metadata={type:$('type').value,title:$('title').value.trim(),issuer:$('issuer').value.trim(),serial:$('serial').value.trim(),description:$('description').value.trim(),fileName:file?.name||'',fileSize:file?.size||0,fileType:file?.type||''};const assetHash=file?await shaFile(file):'';const metadataHash=await shaText(canonical({...metadata,assetHash}));const createdAt=new Date().toISOString(),nonce=rand(),digest=await shaText(`${assetHash||metadataHash}|${metadataHash}|${createdAt}|${nonce}`),sealId=`EVO-${digest.slice(0,8).toUpperCase()}-${digest.slice(8,16).toUpperCase()}-${digest.slice(16,24).toUpperCase()}`;const rec={version:'EVO-SEAL-V0',sealId,digest,assetHash,metadataHash,createdAt,nonce,...metadata,networkAnchor:'OFFCHAIN-DEMO',tokenCharged:'0 EVO'};const r=load();r.push(rec);save(r);$('createResult').className='result';$('createResult').innerHTML=rows(rec)+`<div class="actions"><button id="copyId" class="btn">Copiar Seal ID</button><button id="exportCert" class="btn gold">Exportar JSON</button></div>`;$('copyId').onclick=()=>navigator.clipboard.writeText(rec.sealId).then(()=>toast('Seal ID copiado'));$('exportCert').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(rec,null,2)],{type:'application/json'}));a.download=`${rec.sealId}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};renderList();toast('Sello local creado')}catch(err){toast(err.message)}};
async function verify(){const s=load().find(x=>x.sealId===$('verifyId').value.trim()),out=$('verifyResult');if(!s){out.className='result';out.innerHTML='<span class="status bad">✕ UNKNOWN</span><p>Ese sello no existe en el registro local de este navegador.</p>';return}let extra='';const f=$('verifyFile').files[0];if(f&&s.assetHash){const same=(await shaFile(f))===s.assetHash;extra=same?'<p><span class="status ok">✓ FILE HASH MATCH</span></p>':'<p><span class="status bad">✕ FILE MODIFIED / DIFFERENT</span></p>'}out.className='result';out.innerHTML=rows(s,extra)}
$('verifyBtn').onclick=verify;$('clearBtn').onclick=()=>{$('sealForm').reset();$('createResult').className='empty';$('createResult').textContent='Todavía no creaste un sello.'};
$('walletBtn').onclick=async()=>{if(!window.ethereum)return toast('No se detectó wallet EVM');try{const [a]=await ethereum.request({method:'eth_requestAccounts'});$('walletBtn').textContent=`${a.slice(0,6)}…${a.slice(-4)}`;if(!$('issuer').value)$('issuer').value=a;toast('Wallet conectada. V0 no firma ni mueve fondos.')}catch{toast('Conexión cancelada')}};
renderList();console.info('EVO Seal V0',{token,mode:'NO-CUSTODY / NO-TOKEN-MOVEMENT'});