'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const edge=fs.readFileSync(path.join(root,'supabase/functions/evo-reality-continuity/index.ts'),'utf8');
const migration=fs.readFileSync(path.join(root,'supabase/migrations/20260823181500_reality_continuity_authority_v400.sql'),'utf8');
const workflow=fs.readFileSync(path.join(root,'.github/workflows/evo-security-gate.yml'),'utf8');
assert(edge.includes('evo_register_reality_checkpoint_authoritative'));
assert(!edge.includes('.from("evo_reality_snapshots").insert(row)'));
assert(edge.includes('atomicAuthority: true'));
assert(migration.includes("pg_advisory_xact_lock(pg_catalog.hashtextextended('evo-asset-authority|' || v_seal_id, 0))"));
assert(migration.includes("extensions.digest(v_state_canonical,'sha256')"));
assert(migration.includes("extensions.digest(v_continuity_canonical,'sha256')"));
assert(migration.includes('signer_is_not_current_owner'));
assert(migration.includes('stale_previous_root'));
assert(migration.includes('stale_evidence_state'));
assert(migration.includes("set search_path to ''"));
assert(workflow.includes('tests/reality-authority-v400.test.js'));
assert(workflow.includes('20260823181500_reality_continuity_authority_v400.sql'));
assert(workflow.includes('tests/sql/reality-authority-v400.sql'));
console.log('EVO V4.0 Reality Continuity Authority checks passed');
